[tool.poetry]
name = "smart-home-system"
version = "0.1.0"
description = "An open-source smart home and factory automation system"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "."}]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
fastapi = "^0.95.0"
uvicorn = {extras = ["standard"], version = "^0.21.0"}
sqlalchemy = "^2.0.0"
pydantic = "^2.0.0"
opencv-python = "^4.7.0"
numpy = "^1.24.0"
pillow = "^9.5.0"
pyyaml = "^6.0"
python-multipart = "^0.0.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
black = "^23.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
